### PR TITLE
Xapian2 support

### LINKED ISSUE #217: Omitting * from end of range doesn't search correctly.
`field:...end` works however `field:start..` does not and requires `field:start..*` to work.

I _think_ the xapian parser specifies that omitting the star is valid, so I add it myself to all range tokens before submitting them to xapian_backend.

### LINKED ISSUE #236: SWIG type mismatch in auto_query
Using django-haystack, with xapian-haystack backend, enter a search query that contains two consecutive periods, preceeded by, or followed by, a non-whitespace character, and it crashes on auto_query.

```python
from haystack.query import SearchQuerySet
sqs = SearchQuerySet()
list(sqs.auto_query('..a'))  # 'a..', '...', but not '.. a', 'a ..', '.. .'
```

```
TypeError: SWIG director type mismatch in output value of type '(Xapian::valueno, std::string, std::string)'
Additional information:
Wrong number or type of arguments for overloaded function 'QueryParser_parse_query'.
  Possible C/C++ prototypes are:
    Xapian::QueryParser::parse_query(std::string const &,unsigned int,std::string const &)
    Xapian::QueryParser::parse_query(std::string const &,unsigned int)
    Xapian::QueryParser::parse_query(std::string const &)
```

Versions:

* django-haystack 3.3.0
* xapian-haystack 3.1.0
* python 3.12.3
* xapian 1.4.22

### LINKED ISSUE #239: Xapian 2 support
Xapian 2.0.0 is close to release - currently we're on the second release candidate:

https://lists.xapian.org/pipermail/xapian-discuss/2026-March/thread.html

Testing experimental Debian packages uncovered that xapian-haystack is using the `ValueRangeProcessor` class which was deprecated in 1.4.x and removed in 2.0.0:

```
 94s Traceback (most recent call last):
 94s   File "<string>", line 1, in <module>
 94s     import xapian_backend; print(xapian_backend)
 94s     ^^^^^^^^^^^^^^^^^^^^^
 94s   File "/usr/lib/python3/dist-packages/xapian_backend.py", line 108, in <module>
 94s     class XHValueRangeProcessor(xapian.ValueRangeProcessor):
 94s                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
 94s AttributeError: module 'xapian' has no attribute 'ValueRangeProcessor'. Did you mean: 'DateRangeProcessor'?
```

The replacement is to subclass `xapian.RangeProcessor` instead, and return a `xapian.Query` from your `__call__` method (which will typically use `OP_VALUE_RANGE` like the old API was hard-wired to do but could be `OP_VALUE_LE`, `OP_VALUE_GE` or any query object).

Using `RangeProcessor` will work in 1.4.x too.

### PR DESCRIPTION
**Pull request by ojwb**
The existing CI on master seems to have bitrotted and fails if re-run now without changing the repo contents at all.  I've fixed some of the problems, but I don't understand why one of the 3.8 builds fails, nor why all the 3.10 builds fail, so I've just excluded those.  See individual commit messages for details of the errors I ran into.  As I said in #239, I don't develop (or even use) django, haystack or xapian-haystack, and I do very little Python, so I think I'm the wrong person for the job of trying to fix these excluded builds.

The key changes which are actually updating the code for Xapian 2 are in 2bebec928022118eabcc2d6c75807287983e7d94:

```
    Eliminate use of xapian.ValueRangeProcessor
    
    This class was deprecated in Xapian 1.4 and removed in Xapian 2.
    Instead use xapian.RangeProcessor or construct Query objects directly.
    
    This makes xapian-haystack compatible with Xapian 2.  Fixes #239.
    
    Open-ended ranges now build open-ended Xapian range queries, addressing
    two TODO comments.
    
    A range query on an unknown field is now handle gracefully.  Fixes #236.
    
    A range query of type int or float with an open upper end no longer
    requires `*` for the upper end.  Fixes #217.
```

The Xapian 1.5.1 version used in CI is a release candidate for 2.0.0 so that should be adjusted to use 2.0.0 once actually released.

### CODE REVIEW

**Comment by ojwb** [comment]
> The Xapian 1.5.1 version used in CI is a release candidate for 2.0.0 so that should be adjusted to use 2.0.0 once actually released.

2.0.0 is now released so I've pushed an update to test with it.

**Comment by claudep** [comment]
Hi Olly, I just pushed a separate PR where we fixed the test suite and upgraded to recent Pthon/Django versions. May I ask you to rebase your PR on latest master? You should be now able to concentrate to xapian 2 compat only. Sorry for not doing that sooner.

**Comment by asedeno** [comment]
The decrease in coverage technically correct, but a false positive. It comes from dropping the special case for odd minor versions, which reduced the line count by two and the covered line count by one.

**Comment by claudep** [comment]
@asedeno Does your comment implies you are approving this PR?

**Comment by asedeno** [comment]
I have not reviewed the changes in detail, but the wheels build and the tests pass, which satisfies me as a former xapian-haystack user. Note that I am no longer at the job where I was using this, so I haven't actually used this in years.

**Comment by asedeno** [comment]
> @asedeno Does your comment implies you are approving this PR?

@claudep I've looked over this some more. Yes, we should merge this.

**Comment by claudep** [comment]
@ojwb, as we will probably make a release soon after merging this patch, it would be great to have some content for the Changelog related to these changes. Would you agree to suggest something?

**Comment by ojwb** [comment]
I already summarised the changes in the first comment:

```
    Eliminate use of xapian.ValueRangeProcessor
    
    This class was deprecated in Xapian 1.4 and removed in Xapian 2.
    Instead use xapian.RangeProcessor or construct Query objects directly.
    
    This makes xapian-haystack compatible with Xapian 2.  Fixes #239.
    
    Open-ended ranges now build open-ended Xapian range queries, addressing
    two TODO comments.
    
    A range query on an unknown field is now handle gracefully.  Fixes #236.
    
    A range query of type int or float with an open upper end no longer
    requires `*` for the upper end.  Fixes #217.
```
