### ISSUE TITLE
Xapian 2 support

### ISSUE THREAD

**Issue by ojwb** [notanumber/xapian-haystack#239]
Xapian 2.0.0 is close to release - currently we're on the second release candidate:

https://lists.xapian.org/pipermail/xapian-discuss/2026-March/thread.html

Testing experimental Debian packages uncovered that xapian-haystack is using the `ValueRangeProcessor` class which was deprecated in 1.4.x and removed in 2.0.0:

```
 94s Traceback (most recent call last):
 94s   File "<string>", line 1, in <module>
 94s     import xapian_backend; print(xapian_backend)
 94s     ^^^^^^^^^^^^^^^^^^^^^
 94s   File "/usr/lib/python3/dist-packages/xapian_backend.py", line 108, in <module>
 94s     class XHValueRangeProcessor(xapian.ValueRangeProcessor):
 94s                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
 94s AttributeError: module 'xapian' has no attribute 'ValueRangeProcessor'. Did you mean: 'DateRangeProcessor'?
```

The replacement is to subclass `xapian.RangeProcessor` instead, and return a `xapian.Query` from your `__call__` method (which will typically use `OP_VALUE_RANGE` like the old API was hard-wired to do but could be `OP_VALUE_LE`, `OP_VALUE_GE` or any query object).

Using `RangeProcessor` will work in 1.4.x too.

**Comment by ojwb** [comment]
I saw #236 has a link to https://github.com/ietf-tools/mailarchive/commit/83269361dacc4531a914258d950028e36e2b6db3 which looks plausible.  Maybe it should return `xapian.Query(xapian.Query.OP_INVALID)` if nothing matches rather than `xapian.Query()` as that would signal this isn't a range you want to handle rather than adding a match-nothing filter.

**Comment by claudep** [comment]
Thanks for the report! Would be OK to suggest a patch to fix this?

**Comment by ojwb** [comment]
> Thanks for the report! Would be OK to suggest a patch to fix this?

I've been trying to, but your CI seems quite badly bitrotted so I'm struggling to get it fully tested.

I've tried to fix the CI problems, but I don't really understand what most of them even are - I don't develop (or even use) django, haystack or xapian-haystack, and I do very little Python, so I think I'm the wrong person for the job.

I'll clean up the commits on my branch and open a PR, but someone who has more of a clue about the django/haystack/python side is going to need to push it over the line.

**Comment by ojwb** [comment]
PR opened.

I managed to get the majority of the test matrix to pass, so I've just excluded the combinations where I don't understand the error.

**Comment by claudep** [comment]
I released xapian-haystack 4.0.0 today, if anyone want to test...
